### ISSUE TITLE
dyld: Symbol not found: _$s7SwiftUI10AsyncImageVMn

### ISSUE THREAD

**Issue by tuhaisheng** [ming1016/SwiftPamphletApp#101]
app 运行报这个问题

**Comment by TongRy** [comment]
我也遇到了，咋解决呀

**Comment by ming1016** [comment]
@tuhaisheng @TongRy  Xcode 和 macOS 都升到最新版

**Comment by TongRy** [comment]
> 
嗯嗯，发现了，我系统低了需要macOS 12 ^_^

**Comment by TongRy** [comment]
@ming1016 

> @tuhaisheng @TongRy Xcode 和 macOS 都升到最新版

嗯嗯，发现了，我系统低了需要macOS 12 ^_^
