### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by ElegantNorlin** [ming1016/SwiftPamphletApp#102]
编译的时候出现几个err：
xcode并没有注册开发者账号
然后还有一些包的错误

建议：希望作者大大能打包成app供我这样的新手学习呀

**Comment by ming1016** [comment]
OAuth支持后就可以做成打包app了，已在todo列表里。

你提到问题可以通过把 Xcode 和 macOS 都需要升到最新版，如果遇到 swift package 下载不下来的情况，参看这个议题来解决：https://github.com/ming1016/SwiftPamphletApp/issues/88

**Comment by ElegantAnkster** [comment]
> 

谢谢大大回复
xcode和macOS(12.1apple M1 )已经是最新的了
开发者账号现在还没有，package是clashx开全局规则下载的
等大大放出app再用吧，自己编译条件还有点高
提前感谢大大！

**Comment by Andrew5** [comment]
Couldn’t get revision ‘0.13.1^{commit}’:
/Users/jabraknight/Downloads/SwiftPamphletApp-main/SwiftPamphletApp.xcodeproj Missing package product 'SQLite'
/Users/jabraknight/Downloads/SwiftPamphletApp-main/SwiftPamphletApp.xcodeproj Missing package product 'MarkdownUI'
出现了以上3个错误，导致无法编译通过

**Comment by ming1016** [comment]
> Couldn’t get revision ‘0.13.1^{commit}’: /Users/jabraknight/Downloads/SwiftPamphletApp-main/SwiftPamphletApp.xcodeproj Missing package product 'SQLite' /Users/jabraknight/Downloads/SwiftPamphletApp-main/SwiftPamphletApp.xcodeproj Missing package product 'MarkdownUI' 出现了以上3个错误，导致无法编译通过

可以参考 https://github.com/ming1016/SwiftPamphletApp/issues/88#issuecomment-996392248

**Comment by powenn** [comment]
> 编译的时候出现几个err： xcode并没有注册开发者账号 然后还有一些包的错误
> 
> 建议：希望作者大大能打包成app供我这样的新手学习呀

可以不用付費開發者帳號，在本地設置好PAT後連點compile.command或是參考readme的action方法

**Comment by powenn** [comment]
> 谢谢大大回复
> xcode和macOS(12.1apple M1 )已经是最新的了
> 开发者账号现在还没有，package是clashx开全局规则下载的
> 等大大放出app再用吧，自己编译条件还有点高
> 提前感谢大大！

補充個詳細，git clone 專案到本地，只須設定PAT(personal access token)就行，不用進xcode設定帳號，連點兩下compile.command就會造出app檔案，action則是設定PAT到你fork的repository中action設定action secreta，命名PAT，數值就是你的PAT很長一串那個，之後手動啟用action一次，等個三分鐘你就能下載檔案了
