### ISSUE TITLE
Xcode Version 13.0 (13A233) 一堆语法的问题

### ISSUE THREAD

**Issue by toufuissweet** [ming1016/SwiftPamphletApp#105]
xcode12.2打开不了，用xcode13打开都是swiftUI的语法问题，swiftUI比较生疏，不敢乱改，看了大部分都是闭包的语法问题
![截屏2021-12-08 下午5 29 52](https://user-images.githubusercontent.com/48481597/145183865-872324a8-591d-4cd9-a449-cb1959c17d73.png)
![截屏2021-12-08 下午5 30 23](https://user-images.githubusercontent.com/48481597/145183953-46f44834-abec-4279-a28c-b64967dd7d0c.png)

**Comment by ming1016** [comment]
@toufuissweet Xcode 升级到最新版，参看 #91
