### ISSUE TITLE
MAC OS 13.0 Beta版(22A5321d)  提示“无法打开“戴铭的开发小册子.app”，因为Apple无法检查其是否包含恶意软件。”

### ISSUE THREAD

**Issue by 97wow** [ming1016/SwiftPamphletApp#196]
<img width="294" alt="截屏2022-08-19 14 07 36" src="https://user-images.githubusercontent.com/11026453/185554216-fc1b2d58-aeec-44f0-840b-85ee47ee5754.png">
<img width="297" alt="截屏2022-08-19 14 09 28" src="https://user-images.githubusercontent.com/11026453/185554367-8cb97812-614b-48f5-bd65-0c1a17372a91.png">

**Comment by ming1016** [comment]
可以在安全隐私里打开

**Comment by 97wow** [comment]
OK 打开了，感谢。
