### ISSUE TITLE
Github Action build fail

### ISSUE THREAD

**Issue by WanQuanXie** [ming1016/SwiftPamphletApp#199]
作者好，我想通过 [编译方式](https://github.com/ming1016/SwiftPamphletApp/issues/115) 里的云编译 —— Github Action workflow 方式进行打包编译，但是每次不管是主动 run action 还是通过 pull 项目来触发，action 执行都是失败的。以下是失败的日志：

<img width="1394" alt="image" src="https://github.com/ming1016/SwiftPamphletApp/assets/8021137/dd8630ee-67b8-44e1-bcaf-90a20d4d8017">

想知道是不是某个包的版本需要升级了？

**Comment by lbioser** [comment]
Xcode升级到最新版本

**Comment by WanQuanXie** [comment]
> Xcode升级到最新版本

@lbioser 成了！感谢感谢
