### ISSUE TITLE
多个操作异常卡顿。

### ISSUE THREAD

**Issue by SilverMQL** [ming1016/SwiftPamphletApp#203]
系统：macOS 15Beta
软件版本：App Store最新版。
卡顿操作：
- Apple技术页下某篇具体文章，滚动查看内容。
- 整个窗口拖动边框放大缩小窗口。
- 除了刚打开APP时，其它时候的切换文章。

**Comment by ming1016** [comment]
App Store 版本已更新，做了些兼容适配，优化了文章读取过程。
