### ISSUE TITLE
Which Xcode and Mac OS version required?

### ISSUE THREAD

**Issue by JackLu2012** [ming1016/SwiftPamphletApp#73]
Hi Ming,

I'm using Xcode 13 in Mac 11.5.2 to build your project and it throws massive errors. Can you please give me more info on the version? Appreciate your help!

**Comment by ming1016** [comment]
Xcode 13.1 and macOS 12.0.1.  SwiftPamphlet deployment target is 12.0

**Comment by BOOMBOOMTom** [comment]
> 

dyld: Symbol not found: _$s7SwiftUI10AsyncImageVMn
Macos 11.6,是不是需要更新到Macos 12?

**Comment by ming1016** [comment]
> 

Xcode 也升下吧

**Comment by ming1016** [comment]
> 

Xcode 也升下吧

**Comment by ming1016** [comment]
> > 
> 
> dyld: Symbol not found: _$s7SwiftUI10AsyncImageVMn Macos 11.6,是不是需要更新到Macos 12?

@BOOMBOOMTom Xcode 也升下吧

**Comment by BOOMBOOMTom** [comment]
> > > 
> > 
> > 
> > dyld：找不到符号：_$s7SwiftUI10AsyncImageVMn Macos 11.6，是不是需要更新到Macos 12？
> 
> @BOOMBOOMTom Xcode 也升下吧

Xcode已是最新,这就升级Macos,谢谢戴老师
