### ISSUE TITLE
请问markdownui一直更新不下来是什么原因

### ISSUE THREAD

**Issue by reinstorage** [ming1016/SwiftPamphletApp#88]
![image](https://user-images.githubusercontent.com/58544796/143546673-1561c778-bb23-4f42-9efd-db141cdbd7e0.png)
请问markdownui一直更新不下来是什么原因

**Comment by ming1016** [comment]
他的依赖比较多，详细看在这里，https://github.com/gonzalezreal/MarkdownUI/blob/main/Package.swift 。换个访问github快的网络环境试试？

**Comment by reinstorage** [comment]
> 他的依赖比较多，详细看在这里，https://github.com/gonzalezreal/MarkdownUI/blob/main/Package.swift 。换个访问github快的网络环境试试？

明白  谢谢

**Comment by tigerzhang08** [comment]
失败后如何重新获取 markdownui ？重新打开工程，也没有再次获取。

**Comment by reinstorage** [comment]
> 失败后如何重新获取 markdownui ？重新打开工程，也没有再次获取。

一直没有获取成功过，翻墙也没有成功，报错就是网络的问题，不知道具体的原因

**Comment by superRuan** [comment]
me too

**Comment by ming1016** [comment]
@reinstorage @tigerzhang08 @superRuan 可以参看这篇解决办法，https://www.jianshu.com/p/953220424556

**Comment by DargonLee** [comment]
一直同步不下来，本地库引用也不行 要疯了。GitHub浏览器快但是Xcode依旧慢

**Comment by Kuluso** [comment]
@DargonLee @ming1016 在Xcode的File->Packages->Reset Package Caches
执行完后 会重新拉取依赖的内容的

**Comment by DargonLee** [comment]
![image](https://user-images.githubusercontent.com/13093607/144155137-19b0f1cd-2f6c-47ab-ab16-d9c2f4fb9fc5.png)
@Kuluso 
试了 每次都会有一个失败的库 拉取不下来

**Comment by dyljqq** [comment]
可以尝试使用vpn去下载。默认的swift package的下载是不走代理的。

**Comment by DargonLee** [comment]
@dyljqq 你的意思是开全局代理吗

**Comment by ming1016** [comment]
代理可以在路由器上设置，直接走代理可能还是会慢

**Comment by dyljqq** [comment]
> 
直接在路由器上设置成本过高了，可以尝试通过shell命令打开xcode，这样你在shell里设置代理后，xcode会走代理吧，还是万恶的天朝的啊，github都给墙。

**Comment by qq345386817** [comment]
> > 
> 
> 直接在路由器上设置成本过高了，可以尝试通过shell命令打开xcode，这样你在shell里设置代理后，xcode会走代理吧，还是万恶的天朝的啊，github都给墙。

👍🏻 在 Terminal 里执行 `xcodebuild -project SwiftPamphletApp.xcodeproj` ，终于把依赖下载成功了

**Comment by LuDamon** [comment]
> > > 
> > 
> > 
> > 直接在路由器上设置成本过高了，可以尝试通过shell命令打开xcode，这样你在shell里设置代理后，xcode会走代理吧，还是万恶的天朝的啊，github都给墙。
> 
> 👍🏻 在 Terminal 里执行 `xcodebuild -project SwiftPamphletApp.xcodeproj` ，终于把依赖下载成功了

成功了。另外 github.com 的这个 ip ping 的速度比较快，可以在 hosts 中加入。
52.69.186.44 github.com

**Comment by DargonLee** [comment]
> > > > 
> > > 
> > > 
> > > 直接在路由器上设置成本过高了，可以尝试通过shell命令打开xcode，这样你在shell里设置代理后，xcode会走代理吧，还是万恶的天朝的啊，github都给墙。
> > 
> > 
> > 👍🏻 在 Terminal 里执行 `xcodebuild -project SwiftPamphletApp.xcodeproj` ，终于把依赖下载成功了
> 
> 成功了。另外 github.com 的这个 ip ping 的速度比较快，可以在 hosts 中加入。 52.69.186.44 github.com

> 在改完hosts之后，最好执行下 `sudo killall -HUP mDNSResponder;say DNS cache has been flushed` 来刷新下DNS

**Comment by husangen** [comment]
试了很久不行，最后依赖库全下载本地，才跑起来

**Comment by husangen** [comment]
![image](https://user-images.githubusercontent.com/5366062/144533552-dab05d55-c80e-4496-a1c1-0941c79c8288.png)

试了很久不行，最后把依赖库全下载到本地，才跑起来

**Comment by husangen** [comment]
![image](https://user-images.githubusercontent.com/5366062/144534001-9ae819d6-1442-46bc-928b-69d3231b5336.png)
试了很久都不行，最后全部下载到本地，才跑起来😂

**Comment by tinowu205** [comment]
由于Xcode自身不走代理，所以开全局模式也不行，但可以用Proxifier实现全局代理，亲测有效。

**Comment by dukaibo57** [comment]
我是 sqlite下不来～ 问下怎么弄啊？

**Comment by Yaanco** [comment]
> 我是 sqlite下不来～ 问下怎么弄啊？

试了好几种方法，不是这个库下不来就是那个库下不来，心好累😭

**Comment by dukaibo57** [comment]
![image](https://user-images.githubusercontent.com/47267361/144561589-cb0f788b-ea10-4802-aa94-9c16de2247c5.png)
就是下不来 还有下面的ssl 那个问题 就是token已经配置过了

**Comment by dukaibo57** [comment]
> 就是那个库下不来，

是啊～ 我也一样，然后简书上的第二个方案 error: root manifest not found

**Comment by cocoonbud** [comment]
> 

你挂梯子拉吧。这里的方案二我也一样不行

**Comment by Kuluso** [comment]
又不想挂梯子，还不想每次都手动处理。可以参考一下
[Github520](https://github.com/521xueweihan/GitHub520)
这个开源项目，配合SwithHosts的自动更新，很方便。后续关于GitHub的大多数问题都能解决

**Comment by SinterChen** [comment]
很多人用ss代理吧，简单一点的话就是用**Proxifier**软件，把ss代理转成全局代理
ss代理很多时候只有浏览器走，其他软件并不走。如Spotify。
如果挂的是VPN的话应该是没这个问题

**Comment by alreadyIN** [comment]
xcodebuild -resolvePackageDependencies -scmProvider system

xcodebuild -project SwiftPamphletApp.xcodeproj

**Comment by alreadyIN** [comment]
Step1:
cd SwiftPamphletApp root path
Step2:
xcodebuild -resolvePackageDependencies -scmProvider system
Step3:
xcodebuild -project SwiftPamphletApp.xcodeproj

通过这两行命令解决了。可能需要root权限

**Comment by T-Mux** [comment]
楼上的方法个人觉得都还不够简单。提供一个我觉得最简单的方法：

在根目录找到 `compile.command` 文件，用编辑器打开，在文件的最前面把自己网络的 **终端代理命令** 填上，类似这样

![截屏2021-12-19 下午12 14 27-redacted_dot_app](https://user-images.githubusercontent.com/33898918/146663683-8d3bedc7-d358-4e9b-a215-525f551ee5a2.png)

然后执行这个文件，即可完成编译。两个注意事项：1.文件夹名称要确保是 `SwiftPamphletApp` 2.Token别忘记填上

**Comment by Sookie7** [comment]
Xcode 13.2 会报错，降级到Xcode 13.1 ，重新添加markdownUI 可以运行

**Comment by ming1016** [comment]
> 



> Xcode 13.2 会报错，降级到Xcode 13.1 ，重新添加markdownUI 可以运行

Xcode 13.2不要从 App Store下，不然Swift package用不了，新Xcode要从https://developer.apple.com/download/release/ 下，问题反馈见https://developer.apple.com/forums/thread/696504

**Comment by alreadyIN** [comment]
> > 
> 
> > Xcode 13.2 会报错，降级到Xcode 13.1 ，重新添加markdownUI 可以运行
> 
> Xcode 13.2不要从 App Store下，不然Swift package用不了，新Xcode要从https://developer.apple.com/download/release/ 下，问题反馈见https://developer.apple.com/forums/thread/696504

从App Store下载安装，安装能花掉一天一夜的时间，😂，反正我总是从官网下载xip包来安装，快多了

**Comment by sunshine181** [comment]
> 楼上的方法个人觉得都还不够简单。提供一个我觉得最简单的方法：
> 
> 在根目录找到 `compile.command` 文件，用编辑器打开，在文件的最前面把自己网络的 **终端代理命令** 填上，类似这样
> 
> ![截屏2021-12-19 下午12 14 27-redacted_dot_app](https://user-images.githubusercontent.com/33898918/146663683-8d3bedc7-d358-4e9b-a215-525f551ee5a2.png)
> 
> 然后执行这个文件，即可完成编译。两个注意事项：1.文件夹名称要确保是 `SwiftPamphletApp` 2.Token别忘记填上

在哪个根目录啊

**Comment by T-Mux** [comment]
> > 楼上的方法个人觉得都还不够简单。提供一个我觉得最简单的方法：
> > 在根目录找到 `compile.command` 文件，用编辑器打开，在文件的最前面把自己网络的 **终端代理命令** 填上，类似这样
> > ![截屏2021-12-19 下午12 14 27-redacted_dot_app](https://user-images.githubusercontent.com/33898918/146663683-8d3bedc7-d358-4e9b-a215-525f551ee5a2.png)
> > 然后执行这个文件，即可完成编译。两个注意事项：1.文件夹名称要确保是 `SwiftPamphletApp` 2.Token别忘记填上
> 
> 在哪个根目录啊

作者的仓库文件里有，直接把整个仓库文件下载到本地就行

<img width="1145" alt="截屏2021-12-21 下午8 50 03" src="https://user-images.githubusercontent.com/33898918/146933038-107c6d25-b15c-4b60-bb68-2556b5519de4.png">

**Comment by sunshine181** [comment]
> > > 楼上的方法个人觉得都还不够简单。提供一个我觉得最简单的方法：
> > > 在根目录找到 `compile.command` 文件，用编辑器打开，在文件的最前面把自己网络的 **终端代理命令** 填上，类似这样
> > > ![截屏2021-12-19 下午12 14 27-redacted_dot_app](https://user-images.githubusercontent.com/33898918/146663683-8d3bedc7-d358-4e9b-a215-525f551ee5a2.png)
> > > 然后执行这个文件，即可完成编译。两个注意事项：1.文件夹名称要确保是 `SwiftPamphletApp` 2.Token别忘记填上
> > 
> > 
> > 在哪个根目录啊
> 
> 作者的仓库文件里有，直接把整个仓库文件下载到本地就行
> 
> <img alt="截屏2021-12-21 下午8 50 03" width="1145" src="https://user-images.githubusercontent.com/33898918/146933038-107c6d25-b15c-4b60-bb68-2556b5519de4.png">

搞好了，主要问题是从App Store下载的Xcode有bug，swift package manager有问题，从开发者中心下载XIP

**Comment by pulinghao** [comment]
在host里 设置
`52.192.72.89    github.com`
然后在工程根目录下再运行
`xcodebuild -resolvePackageDependencies -scmProvider system`
就解决了，亲测可用

**Comment by xuanInitial** [comment]
先在终端ping 一下github.com

**Comment by xuanInitial** [comment]
上面的大部分方法都尝试过终于成功了，最后成功的方式如下：
1.开代理全局模式
2.多试几次耐心点[捂脸]

**Comment by VictDog** [comment]
> ![image](https://user-images.githubusercontent.com/5366062/144534001-9ae819d6-1442-46bc-928b-69d3231b5336.png) 试了很久都不行，最后全部下载到本地，才跑起来😂

下载到本地也不行

**Comment by VictDog** [comment]
> 他的依赖比较多，详细看在这里，https://github.com/gonzalezreal/MarkdownUI/blob/main/Package.swift 。换个访问github快的网络环境试试？

能编译一个dmg出来吗，各种方法都试过了，还是不行，心累~

**Comment by Free-am** [comment]
我自己编译了个dmg，方便依赖更新不下来的同学安装，基于当前时间（2022年01月11日15:26:17）是最新代码，当然这里面内容本身就是动态更新的，所以问题不大，更新代码也是软件使用体验更新。 ps:感谢大佬出的这个工具，方便学习Swift（^_^）

[戴铭的Swift小册子dmg.zip](https://github.com/KwaiAppTeam/SwiftPamphletApp/files/7844501/Swift.dmg.zip)

**Comment by ming1016** [comment]
> > 他的依赖比较多，详细看在这里，https://github.com/gonzalezreal/MarkdownUI/blob/main/Package.swift 。换个访问github快的网络环境试试？
> 
> 能编译一个dmg出来吗，各种方法都试过了，还是不行，心累~

现在可以直接下载 dmg 了，地址见 README

**Comment by liunianhuaguoyanxi** [comment]
主要原因是Xcode不走代理，我也是通过Proxifier解决的
https://www.jianshu.com/p/13a825e034c2

**Comment by jidawpc** [comment]
作者。这个要求最低mac os12的系统么。电脑14年版本的系统11.6，没法升级到12系统咋办。我把项目配置兼容降低到11.2，但是
The following build commands failed:
	CompileSwift normal arm64 (in target 'SwiftPamphletApp' from project 'SwiftPamphletApp')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftPamphletApp' from project 'SwiftPamphletApp')
	CompileSwift normal x86_64 (in target 'SwiftPamphletApp' from project 'SwiftPamphletApp')
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'SwiftPamphletApp' from project 'SwiftPamphletApp')

**Comment by ming1016** [comment]
> 作者。这个要求最低mac os12的系统么。电脑14年版本的系统11.6，没法升级到12系统咋办。我把项目配置兼容降低到11.2，但是 The following build commands failed: CompileSwift normal arm64 (in target 'SwiftPamphletApp' from project 'SwiftPamphletApp') CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftPamphletApp' from project 'SwiftPamphletApp') CompileSwift normal x86_64 (in target 'SwiftPamphletApp' from project 'SwiftPamphletApp') CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'SwiftPamphletApp' from project 'SwiftPamphletApp')

因为用了 SwiftUI 新特性

**Comment by jidawpc** [comment]
> 



> 

有能兼容11.6之内的老版本么。没有最新的特性的version也ok的，想收藏学习一下

**Comment by telami** [comment]
楼上的各位，还有一个终极大招，如果解决了问题，别忘了点赞~

把github的项目导入到[码云](https://gitee.com/)，然后用码云的链接，速度超快
