### ISSUE TITLE
Xcode 版本兼容

### ISSUE THREAD

**Issue by Saberwhy** [ming1016/SwiftPamphletApp#91]
你好，我现在使用Xcode 13.0，但是打开项目很多报错。
![image](https://user-images.githubusercontent.com/20423638/143823155-ab736485-7093-4446-94b1-f012f277bf06.png)

**Comment by ming1016** [comment]
macOS也要升呢

**Comment by Saberwhy** [comment]
Mac 版本 也是最新 12.0.1 (21A559)

**Comment by ming1016** [comment]
@RookiePyl @Saberwhy 刚才新提交了一个，再试试看

**Comment by Saberwhy** [comment]
我升级Xcode 13.1 就没有问题了。

**Comment by RookiePyl** [comment]
> 我升级Xcode 13.1 就没有问题了。

感谢！
我升级到Xcode 13.1  就可以了。
