### ISSUE TITLE
关于Swift Package Manager 同步GitHub上的代码频繁失败的建议

### ISSUE THREAD

**Issue by DargonLee** [ming1016/SwiftPamphletApp#94]
由于源码里面需要用户的GitHub的私有token，是不是可以在App启动的时候提示用户输入自己的token值。然后再进入程序的主程序界面。这样就可以即发布源码，又可以编译成dmg文件放在release里面，供大家下载了。

**Comment by ming1016** [comment]
建议不错，已列入todo

**Comment by ooopscc** [comment]
@ming1016 生成 token 时的必要权限能说明下么？

**Comment by ming1016** [comment]
@ooopscc 可以说是调试使用 ming1016/SwiftPamphletApp 应用所需，或者是访问 GitHub API

**Comment by ooopscc** [comment]
@ming1016 这个理解，我的意思是我在生成时应该选 token 需要哪个权限，比如 admin／gist 这些是肯定不需要的。感觉可以在 readme 里面补充下。

**Comment by ming1016** [comment]
@ooopscc 说明已补充，多谢
