### ISSUE TITLE
SwiftUI代码报错

### ISSUE THREAD

**Issue by Qph1059** [ming1016/SwiftPamphletApp#95]
环境：mac OS 11.6
           Xcode 13.0
下载完Swift package后，运行项目SwiftUI代码报错，请问是什么原因？
![image](https://user-images.githubusercontent.com/35688058/144164894-e7b48994-4867-4bfd-8ac5-e9cd9953044c.png)

![image](https://user-images.githubusercontent.com/35688058/144164784-d16b6922-b052-4c91-af75-75166046ff4e.png)

**Comment by ming1016** [comment]
@Qph1059 Xcode 升级到13.1

**Comment by Qph1059** [comment]
> @Qph1059 Xcode 升级到13.1

好的 谢谢
