### ISSUE TITLE
乱码issues-62

### ISSUE THREAD

**Issue by Saberwhy** [ming1016/SwiftPamphletApp#96]
https://github.com/ming1016/SwiftPamphletApp/issues/62
![image](https://user-images.githubusercontent.com/20423638/144166792-ea00e5d1-2d84-473f-a79a-e664066e1815.png)
![image](https://user-images.githubusercontent.com/20423638/144166828-d9e74c0d-1e1e-48fe-b290-4554659152b9.png)

**Comment by ming1016** [comment]
这个是用作列表数据的，base64过的json数据。内容在左侧点击”语法速查“里查看。

**Comment by Saberwhy** [comment]
好的，谢谢。
